//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Above"",
            ""id"": ""901b5d20-3482-4003-b38b-c864fa1140ea"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""afadbfa8-1e7b-4b52-89cd-0e4e4f6b20b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""f73e877d-d32a-4d23-a284-8560312204c0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Root"",
                    ""type"": ""Button"",
                    ""id"": ""5efb00f1-1ec9-477c-a22a-9599926072e4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""0fbed4e1-ee45-4689-ae3b-567cb52d0ff5"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""464f97eb-18e7-4cc7-8b34-6c15f8b8dc78"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""df217964-945b-4e1a-8631-c10e11a9857f"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""634ee17a-4b73-4e94-9720-95347a07011e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""left"",
                    ""id"": ""b57ffe0b-bc79-4bc7-a54d-70a508e7e030"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f8990a64-a5d8-42c5-adef-54026473c6b2"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a415871c-4dfc-4938-862a-d8c34fe0e1ee"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7ef27a6b-a3f1-4834-a82c-100f784c0efb"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2374a26-1088-4a6d-b188-807e75af1da2"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""31968afe-7a09-4020-a3d7-c2c8ef536f37"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Root"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0c03ae5-2052-4aa3-bc74-3d94e57d82b5"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Root"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Below"",
            ""id"": ""4a819a9d-0f54-4e1c-b76e-652ef97c6092"",
            ""actions"": [
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Value"",
                    ""id"": ""a2213a35-de01-4212-bc9c-507b841a97eb"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Value"",
                    ""id"": ""54f58b56-2373-42e9-94c6-2d6f39e50afa"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Value"",
                    ""id"": ""2b3b828f-686e-4627-8734-67fea18bfbe3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Value"",
                    ""id"": ""2871bab3-62f8-402d-87ba-3c0a11833404"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6842ce2a-51c2-437f-9392-86eaffbf6e30"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""326db230-9f04-4679-90e7-71f6276f4c48"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""171fb802-caaf-42d8-a5e2-3ea3c97073e6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e000593f-9648-4c1b-a927-1c740c71d3ee"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4ad11bb-b5a4-422a-bffe-c5dc6af4e2c6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b70002d3-91c0-4cae-a924-1f89d68f4461"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""170bdaf8-21a3-4dda-913c-51b6d9733068"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73377476-2d64-494a-9d56-cdd19054bf1c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PlayerControls"",
            ""bindingGroup"": ""PlayerControls"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Above
        m_Above = asset.FindActionMap("Above", throwIfNotFound: true);
        m_Above_Move = m_Above.FindAction("Move", throwIfNotFound: true);
        m_Above_Jump = m_Above.FindAction("Jump", throwIfNotFound: true);
        m_Above_Root = m_Above.FindAction("Root", throwIfNotFound: true);
        // Below
        m_Below = asset.FindActionMap("Below", throwIfNotFound: true);
        m_Below_MoveUp = m_Below.FindAction("MoveUp", throwIfNotFound: true);
        m_Below_MoveDown = m_Below.FindAction("MoveDown", throwIfNotFound: true);
        m_Below_MoveLeft = m_Below.FindAction("MoveLeft", throwIfNotFound: true);
        m_Below_MoveRight = m_Below.FindAction("MoveRight", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Above
    private readonly InputActionMap m_Above;
    private IAboveActions m_AboveActionsCallbackInterface;
    private readonly InputAction m_Above_Move;
    private readonly InputAction m_Above_Jump;
    private readonly InputAction m_Above_Root;
    public struct AboveActions
    {
        private @PlayerControls m_Wrapper;
        public AboveActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Above_Move;
        public InputAction @Jump => m_Wrapper.m_Above_Jump;
        public InputAction @Root => m_Wrapper.m_Above_Root;
        public InputActionMap Get() { return m_Wrapper.m_Above; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(AboveActions set) { return set.Get(); }
        public void SetCallbacks(IAboveActions instance)
        {
            if (m_Wrapper.m_AboveActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_AboveActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_AboveActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_AboveActionsCallbackInterface.OnMove;
                @Jump.started -= m_Wrapper.m_AboveActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_AboveActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_AboveActionsCallbackInterface.OnJump;
                @Root.started -= m_Wrapper.m_AboveActionsCallbackInterface.OnRoot;
                @Root.performed -= m_Wrapper.m_AboveActionsCallbackInterface.OnRoot;
                @Root.canceled -= m_Wrapper.m_AboveActionsCallbackInterface.OnRoot;
            }
            m_Wrapper.m_AboveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Root.started += instance.OnRoot;
                @Root.performed += instance.OnRoot;
                @Root.canceled += instance.OnRoot;
            }
        }
    }
    public AboveActions @Above => new AboveActions(this);

    // Below
    private readonly InputActionMap m_Below;
    private IBelowActions m_BelowActionsCallbackInterface;
    private readonly InputAction m_Below_MoveUp;
    private readonly InputAction m_Below_MoveDown;
    private readonly InputAction m_Below_MoveLeft;
    private readonly InputAction m_Below_MoveRight;
    public struct BelowActions
    {
        private @PlayerControls m_Wrapper;
        public BelowActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveUp => m_Wrapper.m_Below_MoveUp;
        public InputAction @MoveDown => m_Wrapper.m_Below_MoveDown;
        public InputAction @MoveLeft => m_Wrapper.m_Below_MoveLeft;
        public InputAction @MoveRight => m_Wrapper.m_Below_MoveRight;
        public InputActionMap Get() { return m_Wrapper.m_Below; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BelowActions set) { return set.Get(); }
        public void SetCallbacks(IBelowActions instance)
        {
            if (m_Wrapper.m_BelowActionsCallbackInterface != null)
            {
                @MoveUp.started -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveUp;
                @MoveUp.performed -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveUp;
                @MoveUp.canceled -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveUp;
                @MoveDown.started -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveDown;
                @MoveDown.performed -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveDown;
                @MoveDown.canceled -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveDown;
                @MoveLeft.started -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveLeft;
                @MoveRight.started -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_BelowActionsCallbackInterface.OnMoveRight;
            }
            m_Wrapper.m_BelowActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveUp.started += instance.OnMoveUp;
                @MoveUp.performed += instance.OnMoveUp;
                @MoveUp.canceled += instance.OnMoveUp;
                @MoveDown.started += instance.OnMoveDown;
                @MoveDown.performed += instance.OnMoveDown;
                @MoveDown.canceled += instance.OnMoveDown;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
            }
        }
    }
    public BelowActions @Below => new BelowActions(this);
    private int m_PlayerControlsSchemeIndex = -1;
    public InputControlScheme PlayerControlsScheme
    {
        get
        {
            if (m_PlayerControlsSchemeIndex == -1) m_PlayerControlsSchemeIndex = asset.FindControlSchemeIndex("PlayerControls");
            return asset.controlSchemes[m_PlayerControlsSchemeIndex];
        }
    }
    public interface IAboveActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnRoot(InputAction.CallbackContext context);
    }
    public interface IBelowActions
    {
        void OnMoveUp(InputAction.CallbackContext context);
        void OnMoveDown(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
    }
}
